### ISSUE TITLE
Upgrade `iroh-pkarr-node-discovery` to iroh v0.20.0 and pkarr 2.0

### ISSUE THREAD

**Issue by ramfox** [n0-computer/iroh-examples#77]
There are many changes to the pkarr API so upgrading this example is not as straight forward as the others.

**Comment by matheus23** [comment]
WIP branch at https://github.com/n0-computer/iroh-examples/tree/matheus23/pkarr-discovery-0.20

**Comment by dignifiedquire** [comment]
fixed in https://github.com/n0-computer/iroh-examples/pull/78
